name: Publish snapshot to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches: [ci/test-lsp]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Publish 4.2.0-SNAPSHOT
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository -Pproject.version=4.2.0-SNAPSHOT -Pklyx.sign=false